<a href="https://colab.research.google.com/github/htapiagroup/sistemas-distribuidos-evaluacion-intersemestral-vortizmca18/blob/master/Examen1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Víctor Ortiz Pérez
MCA 2018 - 2020
LANIA

In [0]:
!wget https://archive.org/download/nycTaxiTripData2013/trip_data.7z

--2019-06-18 15:50:34--  https://archive.org/download/nycTaxiTripData2013/trip_data.7z
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ia802501.us.archive.org/1/items/nycTaxiTripData2013/trip_data.7z [following]
--2019-06-18 15:50:34--  https://ia802501.us.archive.org/1/items/nycTaxiTripData2013/trip_data.7z
Resolving ia802501.us.archive.org (ia802501.us.archive.org)... 207.241.228.191
Connecting to ia802501.us.archive.org (ia802501.us.archive.org)|207.241.228.191|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4102781969 (3.8G) [application/x-7z-compressed]
Saving to: ‘trip_data.7z’

trip_data.7z        100%[===================>]   3.82G  10.7MB/s    in 9m 22s  

2019-06-18 15:59:56 (6.96 MB/s) - ‘trip_data.7z’ saved [4102781969/4102781969]



In [10]:
!ls

nyc_taxi.csv  sample_data	trip_data_1.csv  yellow_tripdata_2018-01.csv
nyc_taxi.zip  trip_data_10.csv	trip_data.7z	 yellow_tripdata_2018-02.csv


# 1. Adquirir los datos.


1.   Se descargó el archivo mediante el comando: !wget https://archive.org/download/nycTaxiTripData2013/trip_data.7z
2.   Se tardó 9:22 min. -> 3.82G  10.7MB/s

In [0]:
!7z x trip_data.7z -o/content/


7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.30GHz (306F0),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan         1 file, 4102781969 bytes (3913 MiB)

Extracting archive: trip_data.7z
--
Path = trip_data.7z
Type = 7z
Physical Size = 4102781969
Headers Size = 433
Method = LZMA:24
Solid = -
Blocks = 12

  0%      0% - trip_data_1.csv                        1% - trip_data_1.csv                        2% - trip_data_1.csv                        3% - trip_data_1.csv                        4% - trip_data_1.csv                        5% - trip_data_1.csv                      

In [12]:
!ls -lh

total 11G
-rw-r--r-- 1 root root 1.5G Feb  5  2016 nyc_taxi.csv
-rw-r--r-- 1 root root 413M Apr 12  2017 nyc_taxi.zip
drwxr-xr-x 1 root root 4.0K May 31 16:17 sample_data
-rw-r--r-- 1 root root 1.5G Jun 18 16:06 trip_data_10.csv
-rwxr-xr-x 1 root root 2.3G May 12  2014 trip_data_1.csv
-rw-r--r-- 1 root root 3.9G Jun 20  2014 trip_data.7z
-rw-r--r-- 1 root root 737M Aug  3  2018 yellow_tripdata_2018-01.csv
-rw-r--r-- 1 root root 715M Aug  3  2018 yellow_tripdata_2018-02.csv


# 2. Una vez descargado el archivo pueden descomprimirlo usando la siguiente instruccion

Se corrió el comando indicado, pero al obtener el primer archivo se canceló la instrucción con el objetivo de no saturar el entorno de ejecución.

In [0]:
import numpy as np
import pandas as pd
import psutil, os

def huella_memoria():
    '''Regresa la huella de memoria en MB usada por un proceso de Python'''
    mem = psutil.Process(os.getpid()).memory_info().rss
    return (mem / 1024**2)

In [14]:
antes = huella_memoria()
%time df = pd.read_csv('trip_data_1.csv')
despues = huella_memoria()
print ('Huella de memoria: {} MB'.format(despues-antes))
print ('Memoria del sistema: {} MB'.format(sum(df.memory_usage(index=False) /1024**2)))

CPU times: user 57.2 s, sys: 38.5 s, total: 1min 35s
Wall time: 1min 35s
Huella de memoria: 1479.140625 MB
Memoria del sistema: 1578.312759399414 MB


In [15]:
df.shape

(14776615, 14)

In [16]:
df.columns

Index(['medallion', 'hack_license', 'vendor_id', 'rate_code',
       'store_and_fwd_flag', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'trip_time_in_secs', 'trip_distance',
       'pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude'],
      dtype='object')

# 3. Responder las siguientes preguntas:

1.   Cuantas columnas contiene cada archivo de datos descomprimido.
2.   Cuantos renglones tiene cada archivo.

##Después de cargar el archivo con la librería pandas se utiliza la propiedad "shape" para obtener que el archivo cuenta con 14 columnas y 14,776,6145 renglones.

### Las columnas son:

*   medallion
*   hack_license
*   vendor_id
*   rate_code
*   store_and_fwd_flag
*   pickup_datetime
*   dropoff_datetime
*   passenger_count
*   trip_time_in_secs
*   trip_distance
*   pickup_longitude
*   pickup_latitude
*   dropoff_longitude
*   dropoff_latitude

In [17]:
df.head()

medallion  ... dropoff_latitude
0  89D227B655E5C82AECF13C3F540D4CF4  ...        40.751171
1  0BD7C8F5BA12B88E0B67BED28BEA73D8  ...        40.750660
2  0BD7C8F5BA12B88E0B67BED28BEA73D8  ...        40.726002
3  DFD2202EE08F7A8DC9A57B02ACB81FE2  ...        40.759388
4  DFD2202EE08F7A8DC9A57B02ACB81FE2  ...        40.747868

[5 rows x 14 columns]

In [18]:
df.tail()

medallion  ... dropoff_latitude
14776610  B33E71CD9E8FE1BE3B70FEB6E807DD15  ...        40.770672
14776611  ED160B76D5349C8AC1ECF22CD4B8D538  ...        40.724823
14776612  D83F9AC0E33F6F19869C243BE6AB6FE5  ...        40.788158
14776613  04E59442A7DDBCE515E33CD355D866E7  ...        40.770542
14776614  D30BED60331C79E3F7ACD05B325ED42F  ...        40.773636

[5 rows x 14 columns]

In [35]:
# Verificando registros sin Medallón
df[df['medallion'].str.len()<30]

Empty DataFrame
Columns: [medallion, hack_license, vendor_id, rate_code, store_and_fwd_flag, pickup_datetime, dropoff_datetime, passenger_count, trip_time_in_secs, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude]
Index: []

In [36]:
# Verificando registros sin licencia
df[df['hack_license'].str.len()<30]

Empty DataFrame
Columns: [medallion, hack_license, vendor_id, rate_code, store_and_fwd_flag, pickup_datetime, dropoff_datetime, passenger_count, trip_time_in_secs, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude]
Index: []

In [54]:
df['vendor_id'].unique()

array(['CMT', 'VTS'], dtype=object)

In [40]:
# Verificando registros sin vendedor
df[df['vendor_id'].str.len()<3]

Empty DataFrame
Columns: [medallion, hack_license, vendor_id, rate_code, store_and_fwd_flag, pickup_datetime, dropoff_datetime, passenger_count, trip_time_in_secs, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude]
Index: []

In [53]:
df['rate_code'].unique()

array([  1,   2,   4,   5,   3,   6,   8,   0, 210,  28,   7,   9,  65,
       128])

In [47]:
df[df['rate_code']>9]

medallion  ... dropoff_latitude
2540625   F5818A7D75529449112CD423EA58626C  ...        40.719772
2982293   61C22E72D833C1F868293A9DE377CA8E  ...        40.843048
3389092   85666EE5D2EDFDAC22041D2B6ACF0D71  ...        40.744682
4055114   E523F84E85708BCEB9FEB6F7825C0E08  ...        40.745289
6255682   7EC413823306154C3808A882DF771A1E  ...        40.756237
6759185   C499715B8AC7FC95E2E24C56BDB957C9  ...        40.739906
6841339   A38C0393DB4A916A99E4B345B2F70D92  ...        40.756718
6867270   4BA19608138BFFCCAEC0DEB910D5BFBE  ...        40.763000
7035307   E523F84E85708BCEB9FEB6F7825C0E08  ...        40.825195
7096961   F6B90945F15CDB501B0C18E2163BF96E  ...        40.644165
7958549   8C4F18BF18A8ECAB898369409A09CC17  ...        40.768764
10724973  11FB95AC57D4AA4CB82BB2E061C53374  ...        40.715248
11193753  E523F84E85708BCEB9FEB6F7825C0E08  ...        40.714134
11777985  EFB08EF1CDA77CC654234F098E06E90C  ...        40.747898
12513429  41D2AC8217D65CF5B493D009BEC5221E  ...         0.000000
12518428  41D2AC8217D65CF5B493D009BEC5221E  ...         0.000000
12518752  41D2AC8217D65CF5B493D009BEC5221E  ...         0.000000
12642203  41D2AC8217D65CF5B493D009BEC5221E  ...         0.000000

[18 rows x 14 columns]

In [55]:
df['store_and_fwd_flag'].unique()

array(['N', 'Y', nan], dtype=object)

In [58]:
df[df['pickup_datetime'].str.len()<15]

Empty DataFrame
Columns: [medallion, hack_license, vendor_id, rate_code, store_and_fwd_flag, pickup_datetime, dropoff_datetime, passenger_count, trip_time_in_secs, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude]
Index: []

In [59]:
df[df['dropoff_datetime'].str.len()<15]

Empty DataFrame
Columns: [medallion, hack_license, vendor_id, rate_code, store_and_fwd_flag, pickup_datetime, dropoff_datetime, passenger_count, trip_time_in_secs, trip_distance, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude]
Index: []

In [60]:
df['passenger_count'].unique()

array([  4,   1,   2,   3,   5,   6,   0, 208,   9, 255])

In [61]:
df[df['passenger_count']>9]

medallion  ... dropoff_latitude
1261636   ECCBC87E4B5CE2FE28308FD9F2A7BAF3  ...        36.218121
12308722  DCDD025C953CA1BAAA7044C69BCE2D3D  ...       898.293820

[2 rows x 14 columns]

In [62]:
df['trip_time_in_secs'].unique()

array([ 382,  259,  282, ..., 7034, 7749, 5471])

In [2]:
df[df['trip_time_in_secs']>9000]

NameError: ignored